# fly.toml file generated for firefly-sub on 2022-12-09T13:28:20+08:00

app = "firefly-sub"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
dockerfile = "Dockerfile"

[env]
API_MODE = "true"
API_ACCESS_TOKEN = "password"
MANAGED_PREFIX = "https://firefly-sub.fly.dev"

[experimental]
allowed_public_ports = ["8080", "25500"]
auto_rollback = true

[[services]]
http_checks = []
internal_port = ["8080", "25500"]
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
tls_options = { "alpn" = ["h2", "http/1.1"], "versions" = ["TLSv1.2", "TLSv1.3"], }

handlers = ["tls", "http"]
port = "443"
[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[statics]]
guest_path = "/subconverter/sub-web"
url_prefix = "/subconverter/sub-web"
