# fly.toml file generated for firefly-sub on 2022-12-09T12:47:18+08:00

app = "firefly-sub"
kill_signal = "SIGINT"
kill_timeout = "5"
processes = []

[env]
  API_MODE = "true"
  API_TOKEN = "secret"
  MANAGED_PREFIX = "https://firefly-sub.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = "true"

[[services]]
  http_checks = []
  internal_port = "8080"
  processes = ["app"]
  protocol = ["tcp", "udp"]
  script_checks = []
  [services.concurrency]
    hard_limit = "512"
    soft_limit = "512"
    type = "connections"

  [[services.ports]]
    force_https = "true"
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = "3"
    timeout = "2s"
